
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"

import { ContextProvider } from "@/context";

import Sidebar from "@/components/sidebar";

import ModalCart from "./Modal/ModalCart";
import ModalAvatar from "./Modal/ModalAvatar";
import ModalDetailsProducts from "./Modal/ModalDetailsProducts";

import { ToastContainer } from 'react-toastify';
import RouteLoader from "../components/RouterLoader/RouterLoader";
import 'react-toastify/dist/ReactToastify.css';



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (

    <html lang="en">
      <body className={cn("main-h-screen- bg-background font-sans antialiased"
        , inter.className
      )}>
        <RouteLoader />
        <ContextProvider>
          <ToastContainer/>
          <ModalCart/>
          <ModalAvatar/>
          <ModalDetailsProducts/>
          <Sidebar/>
          {children}
        </ContextProvider>
        
    </body>
    </html>
  );
}
